name: 'build-ecs-nodejs'
author: '1up-team'
description: 'Action to build and release Nodejs & ECS repositories'

inputs:
  pkg-token:
    description: 'User token used to integrate with the spring-media GitHub packages for internal libs'
    required: true

  docker-image-tag:
    description: 'Docker image build tag used when pushing to the 1up AWS ECR'
    required: false
    default: 'b${{ github.run_number }}-${{ github.sha }}'
  docker-registry:
    description: 'Docker registry URL used when pushing to the 1up AWS ECR'
    required: false
    default: '933782373565.dkr.ecr.eu-west-1.amazonaws.com'

  aws-region:
    description: 'Aws region used to deploy the infrastructure and push the docker image'
    required: false
    default: 'eu-west-1'

  cluster-name:
    description: 'Aws cluster name used to deploy the infrastructure'
    required: false
    default: 'up-cluster-production'

  staging:
    description: 'Release to staging environment'
    required: false
    default: 'false'

  node-version:
    description: 'Version number used for actions/setup-node'
    required: false
    default: '16'

  up-slack-webhook-url:
    description: 'Slack channel webhook URL used when reporting master build status'
    required: true

  up-aws-access-key-id:
    description: 'AWS access key id secret used to integrate with aws-cli or docker repository'
    required: true
  up-aws-secret-access-key:
    description: 'AWS access secret key secret used to integrate with aws-cli or docker repository'
    required: true

  app-path:
    description: 'Path to the deployable app directory'
    required: false
    default: '.'
  terraform-module-path:
    description: 'Path to the corresponding app terraform directory'
    required: false
    default: 'terraform'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - name: Setup - Validate Inputs
      shell: bash
      run: |
        [[ "${{ inputs.pkg-token }}" ]] || { echo "input 'pkg-token' cannot be blank"; exit 1; }

    - name: ︎Setup - Node js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true

    - name: Setup service name
      run: |
        SERVICE_NAME=${GITHUB_REPOSITORY##*/1up-}
        echo "Service name: $SERVICE_NAME"
        echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
      shell: bash

    - name: ︎Setup - AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.up-aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.up-aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: ECR setup
      uses: aws-actions/amazon-ecr-login@v2

    - name: Docker - build image
      shell: bash
      working-directory: ${{ inputs.app-path }}
      run: |
        DOCKER_IMAGE="${{ inputs.docker-registry }}/${{ env.SERVICE_NAME }}:${{ inputs.docker-image-tag }}"
        docker build -t $DOCKER_IMAGE .
        echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV

    - name: Docker - push image
      shell: bash
      if: github.ref == 'refs/heads/master'
      run: |
        docker push ${{ env.DOCKER_IMAGE }}

    - uses: dorny/paths-filter@v3
      id: infrastructure-changes
      with:
        filters: |
          terraform:
            - 'terraform/**'

    - name: deploy infrastructure
      if: steps.infrastructure-changes.outputs.terraform == 'true'
      uses: spring-media/1up-github-actions@deploy-infrastructure
      with:
        service-name: ${{ env.SERVICE_NAME }}
        pkg-token: ${{ inputs.pkg-token }}
        docker-image-tag: ${{ inputs.docker-image-tag }}
        staging: ${{ inputs.staging }}
        module-path: ${{ inputs.terraform-module-path }}

    - name: Release - on staging
      if: ${{ inputs.staging == 'true' && steps.infrastructure-changes.outputs.terraform == 'false' }}
      uses: sil-org/ecs-deploy@master
      with:
        aws_access_key_cmd: --aws-access-key
        aws_access_key: ${{ inputs.up-aws-access-key-id }}
        aws_secret_key_cmd: --aws-secret-key
        aws_secret_key: ${{ inputs.up-aws-secret-access-key }}
        cluster_cmd: --cluster
        cluster: up-cluster-staging
        image_cmd: --image
        image: ${{ env.DOCKER_IMAGE }}
        region_cmd: --region
        region: ${{ inputs.aws-region }}
        service_name_cmd: --service-name
        service_name: ${{ env.SERVICE_NAME }}
        timeout_cmd: --timeout
        timeout: 600
        profile: ''

    - name: Release - [on master]
      if: github.ref == 'refs/heads/master' && steps.infrastructure-changes.outputs.terraform == 'false'
      uses: sil-org/ecs-deploy@master
      with:
        aws_access_key_cmd: '--aws-access-key'
        aws_access_key: ${{ inputs.up-aws-access-key-id }}
        aws_secret_key_cmd: '--aws-secret-key'
        aws_secret_key: ${{ inputs.up-aws-secret-access-key }}
        cluster_cmd: '--cluster'
        cluster: ${{ inputs.cluster-name }}
        image_cmd: '--image'
        image: ${{ env.DOCKER_IMAGE }}
        region_cmd: '--region'
        region: ${{ inputs.aws-region }}
        service_name_cmd: '--service-name'
        service_name: ${{ env.SERVICE_NAME }}
        timeout_cmd: '--timeout'
        timeout: '600'
        profile: ''

    - name: Report - [on master]
      if: always()
      uses: spring-media/1up-github-actions@send-notifications
      with:
        slack-webhook-url: ${{ inputs.up-slack-webhook-url }}
        parent-job-status: ${{ job.status }}
