name: test any action

on:
  push:
    branches: [ 'test-action' ]
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - if: always()
        shell: bash
        env:
          SUCCESS_MSG: ''
          FAILURE_MSG: ''
        run: |
          SUCCESS_MESSAGE=${{ env.SUCCESS_MSG }}
          FAILURE_MESSAGE=${{ env.FAILURE_MSG }}
          echo "SUCCESS_MESSAGE=${SUCCESS_MESSAGE:-'${{ env.GIT_ACTIONS_URL }} deployed successfully!\n${{ env.GIT_PR_MSG }}'}" >> $GITHUB_ENV
          echo "FAILURE_MESSAGE=${FAILURE_MESSAGE:-':boom: ${{ env.GIT_ACTIONS_URL }} failed!\n${{ env.GIT_PR_MSG }}'}" >> $GITHUB_ENV
