name: test any action

on:
  push:
    branches: [ 'test-action' ]
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: ︎Setup - Checkout
        uses: actions/checkout@v3

      - name: scenario
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('this is not fine')

      - name: monitor scenario
        if: always()
        shell: bash
        run: |
          echo ${{ github.action_status }}
          echo ${{ job.status }}

      - name: Report
        if: always()
        uses: spring-media/1up-github-actions@send-notifications
        with:
          slack-webhook-url: ${{ secrets.UP_SLACK_WEBHOOK_URL }}
          success-message: "Ignore me, i am a success message"
          failure-message: "Ignore me, i am a failure message"
          always-notify: 'true'
