name: test any action

on:
  push:
    branches: [ 'test-action' ]
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: fail on purpose
        shell: bash
        run: |
          cp foo /bar

      - name: Report
        if: always()
        uses: spring-media/1up-github-actions@send-notifications
        with:
          slack-webhook-url: ${{ secrets.UP_SLACK_WEBHOOK_URL }}
          success-message: "Ignore me, i am a success message"
          failure-message: "Ignore me, i am a failure message"
          always-notify: 'true'
