name: test any action

on:
  push:
    branches: [ 'test-action' ]
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - if: always()
        shell: bash
        env:
          SUCCESS_MSG: ''
          FAILURE_MSG: ''
        run: |
          FAILURE_FB=':boom: ${{ env.GIT_ACTIONS_URL }} failed!\n${{ env.GIT_PR_MSG }}'
          SUCCESS_FB='${{ env.GIT_ACTIONS_URL }} deployed successfully!\n${{ env.GIT_PR_MSG }}'
          SUCCESS_MESSAGE=${${{ env.SUCCESS_MSG }}:-$SUCCESS_FB}
          FAILURE_MESSAGE=${${{ env.FAILURE_MSG }}:-$FAILURE_FB}
          echo "SUCCESS_MESSAGE=${SUCCESS_MESSAGE:-$SUCCESS_FB}" >> $GITHUB_ENV
          echo "FAILURE_MESSAGE=${FAILURE_MESSAGE:-$FAILURE_FB}" >> $GITHUB_ENV
          echo $SUCCESS_MESSAGE
          echo $FAILURE_MESSAGE
