name: test any action

on:
  push:
    branches: [ 'test-action' ]
  workflow_dispatch:

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: test
        shell: bash
        env:
          SUCCESS_MSG: ''
          FAILURE_MSG: ''
        run: |
          SUCCESS_FB='${{ env.GIT_ACTIONS_URL }} deployed successfully!\n${{ env.GIT_PR_MSG }}'
          FAILURE_FB=':boom: ${{ env.GIT_ACTIONS_URL }} failed!\n${{ env.GIT_PR_MSG }}'
          SUCCESS_PARAM=${{ env.SUCCESS_MSG }}
          FAILURE_PARAM=${{ env.FAILURE_MSG }}
          SUCCESS_MESSAGE=${SUCCESS_PARAM:-$SUCCESS_FB}
          FAILURE_MESSAGE=${FAILURE_PARAM:-$FAILURE_FB}
          echo "SUCCESS_MESSAGE=$SUCCESS_MESSAGE" >> $GITHUB_ENV
          echo "FAILURE_MESSAGE=$FAILURE_MESSAGE" >> $GITHUB_ENV
          echo "::notice $SUCCESS_MESSAGE"
          echo "::notice $FAILURE_MESSAGE"
